// Viajes de ejemplo. La primera vez que se abre la página se copian a
// localStorage (ver comun.js) y desde ahí la app los lee y los modifica.
// Los que tienen "mio: true" son los viajes que publicó el usuario.
const viajesIniciales = [
  {
    id: 1,
    conductor: "Marta Ruiz",
    iniciales: "MR",
    carrera: "Ingeniería Informática",
    auto: "Fiat Cronos · gris",
    puntaje: 4.9,
    etiqueta: "Mismo grado",
    precio: 2500,
    desde: "Campus Norte",
    hasta: "Plaza España",
    dia: "Hoy",
    salida: "08:15",
    llegada: "08:40",
    plazas: 2,
    preferencias: ["Sin fumar", "Música suave", "Mochila chica"],
    mio: false
  },
  {
    id: 2,
    conductor: "Javier Ortiz",
    iniciales: "JO",
    carrera: "Abogacía",
    auto: "Peugeot 208 · blanco",
    puntaje: 4.7,
    etiqueta: "",
    precio: 2000,
    desde: "Campus Norte",
    hasta: "Estación Sur",
    dia: "Hoy",
    salida: "08:30",
    llegada: "09:00",
    plazas: 2,
    preferencias: ["Sin fumar"],
    mio: false
  },
  {
    id: 3,
    conductor: "Lucía Prat",
    iniciales: "LP",
    carrera: "Arquitectura",
    auto: "Volkswagen Gol · rojo",
    puntaje: 5.0,
    etiqueta: "Recurrente",
    precio: 3000,
    desde: "Residencia Oeste",
    hasta: "Campus Norte",
    dia: "Hoy",
    salida: "08:45",
    llegada: "09:10",
    plazas: 0,
    preferencias: ["Puntualidad"],
    mio: false
  },
  {
    id: 4,
    conductor: "Tomás Herrera",
    iniciales: "TH",
    carrera: "Medicina",
    auto: "Renault Sandero · negro",
    puntaje: 4.8,
    etiqueta: "",
    precio: 1800,
    desde: "Campus Norte",
    hasta: "Plaza España",
    dia: "Hoy",
    salida: "07:50",
    llegada: "08:15",
    plazas: 1,
    preferencias: ["Sin fumar", "Sin música"],
    mio: false
  },
  {
    id: 5,
    conductor: "Camila Rojas",
    iniciales: "CR",
    carrera: "Psicología",
    auto: "Chevrolet Onix · gris",
    puntaje: 4.5,
    etiqueta: "",
    precio: 2200,
    desde: "Plaza España",
    hasta: "Campus Norte",
    dia: "Hoy",
    salida: "13:30",
    llegada: "13:55",
    plazas: 3,
    preferencias: ["Mascotas OK"],
    mio: false
  },
  {
    id: 6,
    conductor: "Valentina Sosa",
    iniciales: "VS",
    carrera: "Ingeniería Informática",
    auto: "Fiat Mobi · azul",
    puntaje: 4.9,
    etiqueta: "Mismo grado",
    precio: 2800,
    desde: "Estación Sur",
    hasta: "Plaza España",
    dia: "Mañana",
    salida: "07:30",
    llegada: "08:00",
    plazas: 4,
    preferencias: ["Música suave"],
    mio: false
  },
  {
    id: 101,
    conductor: "Vos",
    iniciales: "",
    carrera: "",
    auto: "",
    puntaje: 0,
    etiqueta: "",
    precio: 2000,
    desde: "Campus Norte",
    hasta: "Residencia Oeste",
    dia: "Viernes",
    salida: "14:00",
    llegada: "",
    plazas: 0,
    preferencias: [],
    mio: true,
    solicitudes: 0
  },
  {
    id: 102,
    conductor: "Vos",
    iniciales: "",
    carrera: "",
    auto: "",
    puntaje: 0,
    etiqueta: "",
    precio: 2500,
    desde: "Campus Norte",
    hasta: "Plaza España",
    dia: "Lunes",
    salida: "08:15",
    llegada: "",
    plazas: 3,
    preferencias: [],
    mio: true,
    solicitudes: 2
  }
];
